---

path:
    data_root: /tigress/junchaox/tests
    mrc_file: __DATA_ROOT__/empiar10017/{id}.mrc
    star_directory: /tigress/tcomi/aspyre_temp
    star_file: __STAR_DIRECTORY__/{id}.star
    picker_temp_dir: __STAR_DIRECTORY__/temp/
    picker_temp_in: __STAR_DIRECTORY__/temp/{ind}.in
    picker_temp_out: __STAR_DIRECTORY__/temp/{ind}.out

picker:
    # this isn't actually used, but shows how it could be
    # in the snakemake rule, add in {config[picker][options]}
    options: >
        --show_progress
        --another_long_option false

    # number of files to submit as one job
    batch_size:
        8
